default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  port: 3306
  pool: 5
  username: root 
  password: root

development:
  <<: *default
  database: colchonet
  # socket: /opt/lampp/var/mysql/mysql.sock
  port: 3306

test:
  <<: *default
  database: colchonet_test
  # socket: /opt/lampp/var/mysql/mysql.sock
